config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 7 }
  validates :movie, uniqueness: {scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo

  validates :title, uniqueness: true
  validates :overview, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    @list = @bookmark.list
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h2>Leave your Comment</h2>

<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> All the lists are here ! </h1>

<ul>
  <% @lists.each do |list|%>
  <li>
  <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
  <%= link_to list.name, list_path(list) %>
  </li>
  <% end %>
</ul>

<%= link_to 'Create a new list', new_list_path %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>

  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class='nav-show'>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<h2> This is <%= @list.name %></h2>
</div>
<!-- a rajouter ici la liste des films dans la liste -->
<div class='card'>
<% @bookmarks.each do |bookmark| %>

  <div class='card-info'>
    <%= image_tag bookmark.movie.poster_url, alt: 'an image', width: 200 %>
    <div class='info'>
      <h3><%= bookmark.movie.title %></h3>
      <p><%= bookmark.movie.overview %></p>
      <div class='button'>
        <i class="fas fa-star"><%= bookmark.movie.rating %></i>
        <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'%>
      </div>
    </div>
  </div>
  <br>
  <br>
  <% end %>
</div>

<h2>another movie to put in this list?</h2>

<!-- simple form for deux at dont l'endroit ou il est-->
<div class='form'>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>

    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

<%= link_to 'Go back to main page', lists_path %>